version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8000"
    restart: on-failure
    volumes:
      - ./app/:/orm-based-python-project-layout/app/
      - ./tests/:/orm-python-project-layout/tests/
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:secret@db:5432/db_name
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=db_name

volumes:
  postgres_data:
